### ISSUE TITLE
NOTES.txt incorrect

### ISSUE THREAD

**Issue by alexnuttinck** [cetic/helm-fadi#2]
Notes displayed are incorrect. It doesn't use sub-chart informations.

**Comment by banzo** [comment]
we might also want to change `CONGRATULATIONS! FADI has been installed.` to `CONGRATULATIONS! FADI is being installed.`

**Comment by alexnuttinck** [comment]
It is changed to `CONGRATULATIONS! FADI is being installed.`

**Comment by banzo** [comment]
The psql service name printed is incorrect (should be `fadi-postgresql` instead of `fadi-fadi`)

`➜  helm git:(develop) ✗ export POSTGRES_PASSWORD=$(kubectl get secret --namespace fadi fadi-fadi -o jsonpath="{.data.postgresql-password}" | base64 --decode)
Error from server (NotFound): secrets "fadi-fadi" not found
`

**Comment by alexnuttinck** [comment]
The Grafana server can be accessed via port 80 on the following DNS name from within your cluster:
myrelease.default.svc.cluster.local

* Should be myrelease-grafana.default.scv.cluster.local

fix? https://stackoverflow.com/questions/49142353/helm-getting-subchart-service-names

**Comment by alexnuttinck** [comment]
I simplified the NOTES.txt in the 0.2.4 release. We can close this issue.
